version: '3'

services:

    php:
        build: ./backend-laravel
        restart: always
        depends_on:
            - mysql
            - redis
        volumes:
            - ./backend-laravel:/var/www/html
            - /var/www/html/vendor/
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=vk-bot
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - QUEUE_CONNECTION=database
            - VK_API_URL=https://api.vk.com/method/
            - VK_API_VERSION=5.131
            - VK_API_SERVICE_KEY='Защищённый ключ'

    nginx:
        image: nginx
        restart: always
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./configs/nginx:/etc/nginx/conf.d
            - ./backend-laravel:/var/www/html

    vue:
        build: ./frontend-vue
        depends_on:
            - nginx
        ports:
            - "3000:3000"
        volumes:
            - ./frontend-vue:/app
            -  /app/node_modules

    mysql:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: vk-bot
        volumes:
            - ./database:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - php
        ports:
            - "8181:80"
        environment:
            PMA_HOST: mysql

    redis:
        image: redis
        restart: always

    phpredisadmin:
        image: erikdubbelboer/phpredisadmin
        depends_on:
            - redis
        ports:
            - "9191:80"
        environment:
            - REDIS_1_HOST=redis



