services:

    php:
        build: ./backend-laravel
        restart: unless-stopped
        depends_on:
            - mysql
        volumes:
            - ./backend-laravel:/var/www/html
            - /var/www/html/vendor/
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=vk-bot
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - QUEUE_CONNECTION=database
            - PHP_IDE_CONFIG="serverName=DockerServer"
            - VK_API_URL=https://api.vk.com/method/
            - VK_API_VERSION=5.199
            - VK_API_SERVICE_KEY=9078836e9078836e9078836e6a936ad6f7990789078836ef3b669b8e858f8a314638f9c

    nginx:
        image: nginx
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./configs/nginx:/etc/nginx/conf.d
            - ./backend-laravel:/var/www/html

    vue:
        build: ./frontend-vue
        restart: unless-stopped
        depends_on:
            - nginx
        ports:
            - "3000:3000"
        volumes:
            - ./frontend-vue:/app
            - /app/node_modules

    mysql:
        image: mysql:8.3.0
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: vk-bot
        volumes:
            - ./database:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - "8181:80"
        environment:
            PMA_HOST: mysql
