name: VK-BOT Deploy

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: simple-stack
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Deploy to server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  port: ${{ secrets.SERVER_PORT || 22 }}
                  envs: SERVER_HOST,VK_API_SERVICE_KEY
                  script: |
                      export SERVER_HOST="${{ secrets.SERVER_HOST }}"
                      export VK_API_SERVICE_KEY="${{ secrets.VK_API_SERVICE_KEY }}"
                      
                      # Скачиваем и выполняем скрипт развертывания
                      curl -fsSL https://raw.githubusercontent.com/olegopro/vk-bot/main/scripts/deploy.sh | bash
